web_scraping:
    start_page: "https://books.toscrape.com"
    product_name_selector: "#content_inner > article > div.row > div.col-sm-6.product_main > h1"
    product_price_selector: "#content_inner > article > div.row > div.col-sm-6.product_main > p.price_color"
    product_description_selector: "#content_inner > article > p"  
    product_image_selector: "#product_gallery > div > div > div > img"