web_scraping:
    start_page: "https://fabrikacin.com.ua/zhinochi-sukni"
    product_name_selector: ".page-title"
    product_price_selector: ".price-value"
    product_image_selector: "a img"

methods:
  - run_save_to_csv
  - run_save_to_json
  - run_save_to_yaml
  - run_save_to_sqlite
  - run_save_to_mongodb